BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "uptane-ota"
BBFILE_PATTERN_uptane-ota = "^${LAYERDIR}/"

# Priority 10 — our recipes win over base Poky layers (priority 5)
BBFILE_PRIORITY_uptane-ota = "10"

# BitBake errors out if any of these layers are missing from bblayers.conf
LAYERDEPENDS_uptane-ota = "core openembedded-layer swupdate"

# Scarthgap (5.0.x) compatibility declaration
LAYERSERIES_COMPAT_uptane-ota = "scarthgap"

# Machine configs live inside this layer
BBFILES += "${LAYERDIR}/conf/machine/*.conf"
