require conf/machine/qemuarm64.conf

WKS_FILE      = "ab-image-arm64.wks"
IMAGE_FSTYPES = "wic wic.gz ext4"

QB_SYSTEM_NAME    = "qemu-system-aarch64"
QB_MEM            = "-m 1024"
QB_MACHINE        = "-machine virt -cpu cortex-a57"
QB_NETWORK_DEVICE = "virtio-net-device"
QB_DEFAULT_FSTYPE = "wic"
QB_SERIAL_OPT     = "-nographic"

QB_OPT_APPEND:append = " \
    -object can-bus,id=canbus0 \
    -device kvaser_pci,canbus=canbus0 \
"

KERNEL_IMAGETYPE = "Image"
SERIAL_CONSOLES  = "115200;ttyAMA0"
